### PR TITLE
Steve suggestions

### PR DESCRIPTION
**Pull request by SteveBarnett**
Mostly grammar and style changes.

Ferry page is missing?

Some other things I was thinking about:

**light.html**
- Very long! Split into bits?
- Need to say more about ES6 (what is it) and why you might need to use Babel?

**light-css.html**
- Blink isn't in the client's initial blurb?

**light-nodebots.html**
- Covers _all_ the ACs?
- Should we do https://github.com/codex-academy/oh-oh/commit/4ea6cbf2db27baf4c485ba42672e0e910b5d5611 ?

### CODE REVIEW

**Comment by SteveBarnett** [comment]
@avermeulen: whatchafink of these changes?

**Comment by avermeulen** [comment]
@SteveBarnett I see the front matter was missing for ferry.md causing the link not to work.

**Comment by avermeulen** [comment]
@SteveBarnett what do you mean by 'Covers all the ACs?' - I saw what you meant... no specific AC's metioned in the front matter.

**Comment by SteveBarnett** [comment]
@avermeulen Re AC: Assessment Criteria. Does that page cover all the ACs in the Unit Standard,or just some of them?

**Pull request merged**
